server:
  port: 9098
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommdb?useSSL=false
    username: root
    password:
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          show-sql: true
          format-sql: true
    hibernate:
      ddl-auto: create


management:
  server:
    port: 9099
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
eureka:
  client:
    serviceUrl: 
      defaultZone:  http://localhost:8761/eureka/
